name: Image build
on: [pull_request]
jobs:
  build-amd64:
    name: Image build/amd64 thin plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-amd64
          file: Dockerfile

  build-origin:
    name: Image build/origin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download OKD Builder Dockerfile
        run: curl https://raw.githubusercontent.com/okd-project/images/main/builder/Dockerfile -o okd-builder.Dockerfile

      - name: Create root for builder
        run: mkdir root

      - name: Organically build golang builder image
        run: docker build -t local/okdbuilder:latest -f okd-builder.Dockerfile .

      - name: Organically build Multus origin image
        run: docker build -t local/multus-cni:latest-origin -f Dockerfile.openshift .
